name: deep-learning-course-2025-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - jupyterlab>=4
  - notebook
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - graphviz
  - pip
  - pip:
    - "tensorflow[and-cuda]>=2.20.0"
    - keras>=3.11.3
    - keras-nlp>=0.22.2
    - keras-cv==0.9.0
    - tensorflow-datasets>=4.9
    - tensorboard>=2.20.0
    - jupytext>=1.16
    - nbqa>=1.8
    - black>=24.4
    - ruff>=0.6
    - isort>=5.13
    - pre-commit>=3.7
    - pydot>=2.0
    - tqdm>=4.66
